fps = 6000000000000000000
[dbg]
overlays = true

values = [1, 2, 3,
          4, 5, 6, {2.x = 42}]

[[test]]
value = 123

[[test]]
value = 64

[[test]]
boolean = [false, true, true, true, false, {false = true}]

[[test]]
value = {key = "hello \" world"}